apiVersion: v1
kind: Service
metadata:
  name: foodcart-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: foodcart
  ports:
  - name: frontend
    port: 5173
    targetPort: 5173
    nodePort: 30007
  - name: backend
    port: 5000
    targetPort: 5000
    nodePort: 30008
